config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :users
  resources :services do
    resources :bookings, only: :create
  end

  resources :bookings, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :service

  # NOT FOR NOW
  # validates :proposed_price, presence: true
  # validates :status, presence: true

  validates :date, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos


  validates :description, presence: true, length: { minimum: 10 }
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :bookings, dependent: :destroy
  has_many :services, dependent: :destroy
  has_one_attached :photo
  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validates :name, :cpf, :address, :phone, :credit_card, :worker, presence: true
  # validates :cpf, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end

  def create
    @service = Service.find(params[:service_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.service = @service
    if @booking.save
      render turbo_stream: turbo_stream.replace("booking_form", partial: "bookings/confirmed")
    else
      render turbo_stream: turbo_stream.replace("booking_form", partial: "bookings/form", locals: {service: @service, booking: @booking})
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services = Service.all
  end

  def show
    @booking = Booking.new
    @service = Service.find(params[:id])

  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    @service.user = current_user
    # raise
    if @service.save
      redirect_to services_path
    else
      render :new
    end
  end

  #  DEF EDIT
  #    @SERVICE = SERVICE.FIND(PARAMS[:ID])
  #  END
  #  DEF UPDATE
  #   @SERVICE = SERVICE.FIND(PARAMS[:ID])
  #    IF @SERVICE.UPDATE(SERVICE_PARAMS)
  #      REDIRECT_TO SERVICES_PATH
  #    ELSE
  #      RENDER :EDIT
  #    END
  #  END

  # def destroy
  #   @service = Service.find(params[:id])
  #   @service.destroy
  #   redirect_to services_path
  # end

  private

  def service_params
    params.require(:service).permit(:description, :price, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking_form.html.erb
<div class="container">
  <h1 class="mb-4">Qual o melhor dia para sua limpeza?</h1>

  <%= form_with model: [@service, @booking], local: true do |f| %>
  <%= f.label :date, 'Data:' %>
  <%= f.date_field :date %>
  <%= f.submit 'Agendar', class: 'btn btn-outline-newgreen m-4' %>
  <% end %>
  <%= link_to 'Início', root_path %>
</div>

app/views/bookings/_confirmed.html.erb
<h1>Agendamento confirmado!</h1>
<p>
  <%= link_to "Ver todos os agendamentos", bookings_path, class: 'btn btn-outline-newgreen' %>
</p>

app/views/bookings/_form.html.erb
<%= turbo_frame_tag "booking_form" do %>
  <div class="container">
    <h1 class="mb-4">Escolha uma data</h1>

    <%= simple_form_for [service, booking] do |f| %>
      <%= f.input :date, label: 'Data:', as: :string, input_html: { type: 'date' } %>
      <%= f.submit 'Agendar', class: 'btn btn-outline-newgreen m-4' %>
    <% end %>
  </div>
<% end %>

app/views/bookings/index.html.erb
<div class="container">
  <h1 class="text-center p-5"><strong>Seus agendamentos</strong></h1>

  <ul class="cards">
    <% @bookings.each do |booking| %>
      <li class="card-item mb-5">
        <div class="card-body h-100 card">
          <h5 class="card-title"><strong><%= booking.service.user.name %></strong></h5>
          <p class="card-text"><strong>Tipo de serviço: </strong><%= booking.service.description %></p>
          <p class="card-text"><strong>Preço: </strong><%= number_to_currency(booking.service.price, unit: 'R$', format: '%u %n', separator: ',', delimiter: '.') %></p></p>
          <p class="card-text"><strong>Dia: </strong><%= booking.date.strftime('%d/%m/%Y') %></p>
        </div>
      </li>
    <% end %>
  </ul>


  <%# TALVEZ DEPOIS %>
  <%# <nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item">
      <a class="page-link" href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item">
      <a class="page-link" href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav> %>

 <div class="container mb-5 mt-4">
    <%= link_to 'Início', root_path, class: "btn btn-outline-newgreen btn-lg w-100" %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <h1 class="mb-4">Qual o melhor dia para sua limpeza?</h1>

  <%= form_with model: [@service, @booking], local: true do |f| %>
  <%= f.label :date, 'Data:' %>
  <%= f.date_field :date %>
  <%= f.submit 'Agendar', class: 'btn btn-outline-newgreen m-4' %>
  <% end %>
  <%= link_to 'Início', root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CleanEasy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>



  <body>
    <div class="navbar fixed-top navbar-expand-sm navbar-newgreen navbar-lewagon">
      <div class="container-fluid">
        <a class="navbar-brand" href="../#">
          <span class="written-logo"> CleanEasy </span>
        </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
            <li class="nav-item active">
              <a class="btn btn-outline-newgreen btn-link mx-2" href="/users/sign_in"><strong>Entrar</strong></a>
            </li>
            <li class="nav-item">
              <a class="btn btn-outline-newgreen btn-link" href="/users/sign_up"><strong>Cadastrar</strong></a>
            </li>
            <li class="nav-item">
              <a class="btn btn-outline-newgreen btn-link" href="/users/sign_out"><strong>Log out</strong></a>
            </li>
            <li class="nav-item dropdown">
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a>
              </div>
            </li>
        </ul>
      </div>
  </div>
</div>

  <div>
    <%= render "shared/flashes" %>
    <div class="navbar-margin ">
      <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="py-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cglimpeza.com.br/wp-content/uploads/2017/12/2018-01-10-importancia-dos-epis-para-equipes-de-limpeza.jpg); background-size: cover; height: 500px; display: flex; justify-content: center; align-items: center; flex-direction: column; text-align: center;">
    <h1 style="color: white;"><em>Clean Easy</em> – <strong>A Excelência em Limpeza</strong> para o <strong>Seu Espaço</strong>!</h1>
    <h2 style="color: white;">Transforme a sua casa ou empresa com uma limpeza impecável. Confie em profissionais que fazem da limpeza uma verdadeira arte.</h2>
</div>


<div class="container">
  <div class="justify-center p-3">
    <h2>Transforme sua rotina com serviços domésticos de excelência</h2>
    <h3>Descubra as Vantagens Exclusivas que Só a Clean Easy Oferece</h3>
  </div>
  <div class="p-3">
  <h3><strong>Praticidade</strong></h3>
    <ul>
      <li>Garanta seus serviços de forma rápida e fácil! Contrate e pague em menos de um minuto diretamente pelo nosso aplicativo.</p>
    </ul>
    <hr>

    <h3><strong>Qualidade</strong></h3>
      <ul>
        <li>Contamos com profissionais altamente avaliados, com uma média de satisfação superior a 4,6 de 5⭐, garantindo um serviço impecável.
      </ul>
      <hr>

    <h3><strong>Segurança</strong></h3>
      <ul>
        <li>Nosso rigoroso processo de credenciamento e checagens periódicas asseguram que você sempre receba o melhor atendimento, com total confiança.
      </ul>
      <hr>

    <h3><strong>Preço Justo</strong></h3>
      <ul>
        <li>Pague somente pelo tempo necessário, com tarifas transparentes e adaptadas às suas necessidades.
      </ul>
      <hr>
    </div>
    <div class="d-flex justify-content-center">
      <%= link_to "Explore Todos os Serviços", services_path, class: "btn btn-outline-newgreen btn-lg mx-2" %>
      <%= link_to "Cadastre Seus Serviços", new_service_path, class: "btn btn-outline-newgreen btn-lg mx-2" %>
      <%= link_to "Consulte Seus Agendamentos", bookings_path, class: "btn btn-outline-newgreen btn-lg mx-2" %>
    </div>
</div>



<div class="card-category">
  <div class="card">
    <div class="imgcard">
      <img src="https://amz.run/9Uxh" alt="Imagem de um borrifador" class="card-image">
    </div>
    <div class="card-content d-flex flex-column" style="height: 100%;">
      <h2 class="card-title">Limpeza padrão</h2>
      <p class="card-description flex-grow-1">Limpeza de qualidade e eficiência</p>
      <a href="#" class="btn btn-outline-newgreen btn-lg mt-auto">Agendar</a>
    </div>
  </div>

  <div class="card">
    <div class="imgcard">
      <img src="https://amz.run/9Uxg" alt="Imagem de uma vassoura" class="card-image">
    </div>
    <div class="card-content d-flex flex-column" style="height: 100%;">
      <h2 class="card-title">Limpeza pesada</h2>
      <p class="card-description flex-grow-1">Limpeza pesada com qualidade e eficiência</p>
      <a href="#" class="btn btn-outline-newgreen btn-lg mt-auto">Agendar</a>
    </div>
  </div>

  <div class="card">
    <div class="imgcard">
      <img src="https://amz.run/9Uxf" alt="Imagem de uma casa" class="card-image">
    </div>
    <div class="card-content d-flex flex-column" style="height: 100%;">
      <h2 class="card-title">Limpeza pós obra</h2>
      <p class="card-description flex-grow-1">Limpeza pós obra com qualidade e eficiência</p>
      <a href="#" class="btn btn-outline-newgreen btn-lg mt-auto">Agendar</a>
    </div>
   </div>

  <div class="card">
    <div class="imgcard">
      <img src="https://amz.run/9Uxe" alt="Imagem de um caminhão" class="card-image">
    </div>
    <div class="card-content d-flex flex-column" style="height: 100%;">
      <h2 class="card-title">Limpeza pré ou pós mudança</h2>
      <p class="card-description flex-grow-1">Limpeza pré ou pós mudança com qualidade e eficiência</p>
      <a href="#" class="btn btn-outline-newgreen btn-lg mt-auto">Agendar</a>
    </div>
  </div>
</div>

<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Easy Co. 2024
  </div>
</div>

app/views/services/index.html.erb
  <div class="d-flex justify-content-center p-5">
    <h1>Serviços Disponíveis</h1>
  </div>
  <div class="container">
  <div class="row">
    <% @services.each do |service| %>
      <div class="col-md-3 mb-3">
        <div class="card h-100">
          <% if service.description == 'Limpeza padrão' %>
            <img src="https://blog.parafuzo.com/wp-content/uploads/2021/09/household-cleaning-supplies-480x288.jpeg" class="h-100" />
          <% elsif service.description == 'Limpeza pesada' %>
            <img src="https://cdn.casapraticaqualita.com.br/wp-content/uploads/2020/06/2320-para-fazer-uma-limpeza-pesada-voce-vai-orig-2.jpg" class="h-100 "/>
          <% elsif service.description == 'Limpeza pós obra' %>
            <img src="https://whiteningmultiservicos.com.br/wp-content/uploads/2022/06/2022-07-07-produtos-para-limpeza-pos-obra-802x506.jpg" class="h-100" />
          <% else%>
            <img src="https://img.freepik.com/fotos-premium/produtos-de-limpeza-escovas-garrafas-esponjas-trapo-luvas-de-borracha-amarelas-em-fundo-branco_937679-35259.jpg?size=626&ext=jpg&ga=GA1.1.2008272138.1724025600&semt=ais_hybrid" class="h-100" />
          <% end %>
          <div class="card-body">
            <h3 class="card-title"><%= service.description %></h3>
            <h5 class="card-subtitle mb-2 text-muted"><%= service.user.name %></h5>
            <p class="card-text">Preço: <%= number_to_currency(service.price, unit: 'R$', format: '%u %n', separator: ',', delimiter: '.') %></p>
          </div>
          <div class="card-footer">
            <%= link_to "Saiba mais", service_path(service), class: "btn btn-outline-newgreen btn-sm rounded-pill" %>
            <%= link_to 'Editar', edit_service_path(service), class: "btn btn-outline-newgreen btn-sm rounded-pill" %>
            <%= link_to 'Apagar', service, method: :delete, data: { confirm: 'Tem a certeza?' }, class:"btn btn-outline-danger btn-sm rounded-pill" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
 <div class="container mb-5 mt-4">
    <%= link_to 'Início', root_path, class: "btn btn-outline-newgreen btn-lg w-100"%>
</div>
</div>

app/views/services/new.html.erb
<div class="container p-4">
  <%= simple_form_for @service do |f| %>
    <%= f.input :description, collection: ['Limpeza padrão', 'Limpeza pesada', 'Limpeza pós obra', 'Limpeza pré ou pós mudança'], label: 'Descrição', placeholder: 'Escolha uma opção' %>
    <%= f.input :price, label: 'Preço', placeholder: 'Digite o preço' %>
    <%= f.input :photos, label: 'Imagem', as: :file, input_html: { multiple: true }, label: 'Imagens' %>
    <%= f.button :submit, 'Enviar', class: "btn btn-outline-newgreen btn-lg mx-2" %>
  <% end %>
  <br>
  <%= link_to 'Início', root_path, class: "btn btn-outline-newgreen btn-lg mx-2"%>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>